/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCorporationsCorporationIdOutpostsOutpostIdOk :  IEquatable<GetCorporationsCorporationIdOutpostsOutpostIdOk>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCorporationsCorporationIdOutpostsOutpostIdOk" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCorporationsCorporationIdOutpostsOutpostIdOk() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCorporationsCorporationIdOutpostsOutpostIdOk" /> class.
        /// </summary>
        /// <param name="Coordinates">Coordinates (required).</param>
        /// <param name="DockingCostPerShipVolume">docking_cost_per_ship_volume number (required).</param>
        /// <param name="OfficeRentalCost">office_rental_cost integer (required).</param>
        /// <param name="OwnerId">The entity that owns the station (e.g. the entity whose logo is on the station services bar) (required).</param>
        /// <param name="ReprocessingEfficiency">reprocessing_efficiency number (required).</param>
        /// <param name="ReprocessingStationTake">reprocessing_station_take number (required).</param>
        /// <param name="Services">A list of services the given outpost provides (required).</param>
        /// <param name="StandingOwnerId">The owner ID that sets the ability for someone to dock based on standings. (required).</param>
        /// <param name="SystemId">The ID of the solar system the outpost rests in (required).</param>
        /// <param name="TypeId">The type ID of the given outpost (required).</param>
        public GetCorporationsCorporationIdOutpostsOutpostIdOk(GetCorporationsCorporationIdOutpostsOutpostIdCoordinates Coordinates = default(GetCorporationsCorporationIdOutpostsOutpostIdCoordinates), float? DockingCostPerShipVolume = default(float?), long? OfficeRentalCost = default(long?), int? OwnerId = default(int?), float? ReprocessingEfficiency = default(float?), float? ReprocessingStationTake = default(float?), List<GetCorporationsCorporationIdOutpostsOutpostIdService> Services = default(List<GetCorporationsCorporationIdOutpostsOutpostIdService>), int? StandingOwnerId = default(int?), int? SystemId = default(int?), int? TypeId = default(int?))
        {
            // to ensure "Coordinates" is required (not null)
            if (Coordinates == null)
            {
                throw new InvalidDataException("Coordinates is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.Coordinates = Coordinates;
            }
            // to ensure "DockingCostPerShipVolume" is required (not null)
            if (DockingCostPerShipVolume == null)
            {
                throw new InvalidDataException("DockingCostPerShipVolume is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.DockingCostPerShipVolume = DockingCostPerShipVolume;
            }
            // to ensure "OfficeRentalCost" is required (not null)
            if (OfficeRentalCost == null)
            {
                throw new InvalidDataException("OfficeRentalCost is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.OfficeRentalCost = OfficeRentalCost;
            }
            // to ensure "OwnerId" is required (not null)
            if (OwnerId == null)
            {
                throw new InvalidDataException("OwnerId is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.OwnerId = OwnerId;
            }
            // to ensure "ReprocessingEfficiency" is required (not null)
            if (ReprocessingEfficiency == null)
            {
                throw new InvalidDataException("ReprocessingEfficiency is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.ReprocessingEfficiency = ReprocessingEfficiency;
            }
            // to ensure "ReprocessingStationTake" is required (not null)
            if (ReprocessingStationTake == null)
            {
                throw new InvalidDataException("ReprocessingStationTake is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.ReprocessingStationTake = ReprocessingStationTake;
            }
            // to ensure "Services" is required (not null)
            if (Services == null)
            {
                throw new InvalidDataException("Services is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.Services = Services;
            }
            // to ensure "StandingOwnerId" is required (not null)
            if (StandingOwnerId == null)
            {
                throw new InvalidDataException("StandingOwnerId is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.StandingOwnerId = StandingOwnerId;
            }
            // to ensure "SystemId" is required (not null)
            if (SystemId == null)
            {
                throw new InvalidDataException("SystemId is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.SystemId = SystemId;
            }
            // to ensure "TypeId" is required (not null)
            if (TypeId == null)
            {
                throw new InvalidDataException("TypeId is a required property for GetCorporationsCorporationIdOutpostsOutpostIdOk and cannot be null");
            }
            else
            {
                this.TypeId = TypeId;
            }
        }
        
        /// <summary>
        /// Gets or Sets Coordinates
        /// </summary>
        [DataMember(Name="coordinates", EmitDefaultValue=false)]
        public GetCorporationsCorporationIdOutpostsOutpostIdCoordinates Coordinates { get; set; }

        /// <summary>
        /// docking_cost_per_ship_volume number
        /// </summary>
        /// <value>docking_cost_per_ship_volume number</value>
        [DataMember(Name="docking_cost_per_ship_volume", EmitDefaultValue=false)]
        public float? DockingCostPerShipVolume { get; set; }

        /// <summary>
        /// office_rental_cost integer
        /// </summary>
        /// <value>office_rental_cost integer</value>
        [DataMember(Name="office_rental_cost", EmitDefaultValue=false)]
        public long? OfficeRentalCost { get; set; }

        /// <summary>
        /// The entity that owns the station (e.g. the entity whose logo is on the station services bar)
        /// </summary>
        /// <value>The entity that owns the station (e.g. the entity whose logo is on the station services bar)</value>
        [DataMember(Name="owner_id", EmitDefaultValue=false)]
        public int? OwnerId { get; set; }

        /// <summary>
        /// reprocessing_efficiency number
        /// </summary>
        /// <value>reprocessing_efficiency number</value>
        [DataMember(Name="reprocessing_efficiency", EmitDefaultValue=false)]
        public float? ReprocessingEfficiency { get; set; }

        /// <summary>
        /// reprocessing_station_take number
        /// </summary>
        /// <value>reprocessing_station_take number</value>
        [DataMember(Name="reprocessing_station_take", EmitDefaultValue=false)]
        public float? ReprocessingStationTake { get; set; }

        /// <summary>
        /// A list of services the given outpost provides
        /// </summary>
        /// <value>A list of services the given outpost provides</value>
        [DataMember(Name="services", EmitDefaultValue=false)]
        public List<GetCorporationsCorporationIdOutpostsOutpostIdService> Services { get; set; }

        /// <summary>
        /// The owner ID that sets the ability for someone to dock based on standings.
        /// </summary>
        /// <value>The owner ID that sets the ability for someone to dock based on standings.</value>
        [DataMember(Name="standing_owner_id", EmitDefaultValue=false)]
        public int? StandingOwnerId { get; set; }

        /// <summary>
        /// The ID of the solar system the outpost rests in
        /// </summary>
        /// <value>The ID of the solar system the outpost rests in</value>
        [DataMember(Name="system_id", EmitDefaultValue=false)]
        public int? SystemId { get; set; }

        /// <summary>
        /// The type ID of the given outpost
        /// </summary>
        /// <value>The type ID of the given outpost</value>
        [DataMember(Name="type_id", EmitDefaultValue=false)]
        public int? TypeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCorporationsCorporationIdOutpostsOutpostIdOk {\n");
            sb.Append("  Coordinates: ").Append(Coordinates).Append("\n");
            sb.Append("  DockingCostPerShipVolume: ").Append(DockingCostPerShipVolume).Append("\n");
            sb.Append("  OfficeRentalCost: ").Append(OfficeRentalCost).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  ReprocessingEfficiency: ").Append(ReprocessingEfficiency).Append("\n");
            sb.Append("  ReprocessingStationTake: ").Append(ReprocessingStationTake).Append("\n");
            sb.Append("  Services: ").Append(Services).Append("\n");
            sb.Append("  StandingOwnerId: ").Append(StandingOwnerId).Append("\n");
            sb.Append("  SystemId: ").Append(SystemId).Append("\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetCorporationsCorporationIdOutpostsOutpostIdOk);
        }

        /// <summary>
        /// Returns true if GetCorporationsCorporationIdOutpostsOutpostIdOk instances are equal
        /// </summary>
        /// <param name="input">Instance of GetCorporationsCorporationIdOutpostsOutpostIdOk to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCorporationsCorporationIdOutpostsOutpostIdOk input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Coordinates == input.Coordinates ||
                    (this.Coordinates != null &&
                    this.Coordinates.Equals(input.Coordinates))
                ) && 
                (
                    this.DockingCostPerShipVolume == input.DockingCostPerShipVolume ||
                    (this.DockingCostPerShipVolume != null &&
                    this.DockingCostPerShipVolume.Equals(input.DockingCostPerShipVolume))
                ) && 
                (
                    this.OfficeRentalCost == input.OfficeRentalCost ||
                    (this.OfficeRentalCost != null &&
                    this.OfficeRentalCost.Equals(input.OfficeRentalCost))
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                ) && 
                (
                    this.ReprocessingEfficiency == input.ReprocessingEfficiency ||
                    (this.ReprocessingEfficiency != null &&
                    this.ReprocessingEfficiency.Equals(input.ReprocessingEfficiency))
                ) && 
                (
                    this.ReprocessingStationTake == input.ReprocessingStationTake ||
                    (this.ReprocessingStationTake != null &&
                    this.ReprocessingStationTake.Equals(input.ReprocessingStationTake))
                ) && 
                (
                    this.Services == input.Services ||
                    this.Services != null &&
                    this.Services.SequenceEqual(input.Services)
                ) && 
                (
                    this.StandingOwnerId == input.StandingOwnerId ||
                    (this.StandingOwnerId != null &&
                    this.StandingOwnerId.Equals(input.StandingOwnerId))
                ) && 
                (
                    this.SystemId == input.SystemId ||
                    (this.SystemId != null &&
                    this.SystemId.Equals(input.SystemId))
                ) && 
                (
                    this.TypeId == input.TypeId ||
                    (this.TypeId != null &&
                    this.TypeId.Equals(input.TypeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Coordinates != null)
                    hashCode = hashCode * 59 + this.Coordinates.GetHashCode();
                if (this.DockingCostPerShipVolume != null)
                    hashCode = hashCode * 59 + this.DockingCostPerShipVolume.GetHashCode();
                if (this.OfficeRentalCost != null)
                    hashCode = hashCode * 59 + this.OfficeRentalCost.GetHashCode();
                if (this.OwnerId != null)
                    hashCode = hashCode * 59 + this.OwnerId.GetHashCode();
                if (this.ReprocessingEfficiency != null)
                    hashCode = hashCode * 59 + this.ReprocessingEfficiency.GetHashCode();
                if (this.ReprocessingStationTake != null)
                    hashCode = hashCode * 59 + this.ReprocessingStationTake.GetHashCode();
                if (this.Services != null)
                    hashCode = hashCode * 59 + this.Services.GetHashCode();
                if (this.StandingOwnerId != null)
                    hashCode = hashCode * 59 + this.StandingOwnerId.GetHashCode();
                if (this.SystemId != null)
                    hashCode = hashCode * 59 + this.SystemId.GetHashCode();
                if (this.TypeId != null)
                    hashCode = hashCode * 59 + this.TypeId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
