// <auto-generated />
using EVETrader.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EVETrader.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180517122526_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("EVETrader.Core.Model.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BuyerId");

                    b.Property<int>("Destination");

                    b.Property<bool>("Published");

                    b.Property<double>("Tip");

                    b.Property<int?>("TraderId");

                    b.Property<double>("estimatedPrice");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("TraderId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("EVETrader.Core.Model.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Quantity");

                    b.Property<int?>("SalesOrderId");

                    b.Property<int>("TypeID");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("EVETrader.Core.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EVETrader.Core.Model.SalesOrder", b =>
                {
                    b.HasOne("EVETrader.Core.Model.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");

                    b.HasOne("EVETrader.Core.Model.User", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId");
                });

            modelBuilder.Entity("EVETrader.Core.Model.ShoppingList", b =>
                {
                    b.HasOne("EVETrader.Core.Model.SalesOrder", "SalesOrder")
                        .WithMany("ShoppingList")
                        .HasForeignKey("SalesOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
